### PR TITLE
executeCI.ps1: add line number to error

### PR DESCRIPTION
**Pull request by kolyshkin**
Having an error like this:

> 00:00:41.385 ERROR: Failed 'You cannot call a method on a null-valued expression.' at 08/27/2018 19:37:24

is hopeless as one can't possibly figure out where is it
coming from. Let's add a line number to error message.

Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>

### CODE REVIEW

**Comment by jhowardmsft** [comment]
Can you update the date/time nearer the top of the script so that when it runs, you can tell the version more easily (no, not ideal, but better than nothing). Note also there's a PR into moby/moby to put this script into the repo itself, but I can update Jenkins.dockerproject.org RS1 jobs to pick up this change. 

Otherwise LGTM.

Out of interest, what were you running to hit this error?

**Comment by kolyshkin** [comment]
> Can you update the date/time nearer the top of the script

Done. In the process vim made some "improvements" to indentation,
replacing `\0xA0` (non-breaking space) with a simple space. I guess it's for good. 

> Note also there's a PR into moby/moby to put this script into the repo itself

That would be awesome!

> Out of interest, what were you running to hit this error?

https://jenkins.dockerproject.org/job/Docker-PRs-WoW-RS1/21888/console (from https://github.com/moby/moby/pull/37358) and I still don't know the cause :(

**Comment by kolyshkin** [comment]
I have changed the info printed from the line number only to InvocationInfo.PositionMessage which should give a good idea of what file, line, and character the error has happened.

Please note I don't have any powershell experience, nor a way to try out a powershell scripts, so this patch is "purely theoretical", so to say.

**Comment by jhowardmsft** [comment]
Carried in https://github.com/jhowardmsft/docker-w2wCIScripts/pull/29

**Comment by kolyshkin** [comment]
> Note also there's a PR into moby/moby to put this script into the repo itself

@jhowardmsft can you please share a link to that PR?

**Pull request closed without merging**
